name: Context demo -- github

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: print path
        run: | # | 为 yaml 的特定符号，其下可以使用多行文字。
          echo "当前路径为 $(pwd)"
          ls -a
          echo "HOME路径为 $HOME"
          ls $HOME -a

      - name: Show github.action_path
        run: echo "	操作所在的路径 ${{ github.action_path }}"

      - name: Show github.actor
        run: echo "触发用户 ${{ github.actor }}"
      
      - name: Show github.env
        run: echo "运行器上从工作流程命令到设置环境变量的文件路径 ${{ github.env }}"

      - name: github.event_name
        run: echo "触发事件 ${{ github.event_name }}"

      - name: github.event_path
        run: echo "运行器上包含完整事件 web 挂钩负载的文件的路径 ${{ github.event_path }}"

      - name: Show github.workspace
        run: echo "运行器上步骤的默认工作目录 ${{ github.workspace }}"

      - name: Show github.workflow
        run: echo "工作流名称 ${{ github.workflow }}"
      
      - name: Show github.workflow_ref
        run: echo "工作流的引用路径 ${{ github.workflow_ref }}"

      - name: Show github.workflow_sha
        run: echo "工作流文件的提交 SHA ${{ github.workflow_sha }}"

      - name: Show github.repository
        run: echo "所有者和仓库名称 ${{ github.repository }}"

      - name: Show github.repository_id
        run: echo "存储库的 ID ${{ github.repository_id }}"

      - name: Show github.repository_owner
        run: echo "存储库所有者的用户名 ${{ github.repository_owner }}"

      - name: Show github.repository_owner_id
        run: echo "存储库所有者的帐户 ID ${{ github.repository_owner_id }}"

      - name: Show github.repositoryUrl
        run: echo "存储库的 Git URL ${{ github.repositoryUrl }}"

      - name: Show github.sha
        run: echo "触发工作流的提交 SHA ${{ github.sha }}"

      - name: Show github.ref
        run: echo "触发工作流运行的分支或标记的格式完整的参考 ${{ github.ref }}"

      - name: Show github.ref_name
        run: echo "触发工作流运行的分支或标记的短参考名称 ${{ github.ref_name }}"

      - name: Show github.ref_type
        run: echo "触发工作流运行的 ref 类型 ${{ github.ref_type }}"

      - name: Show run ID
        run: echo "运行ID ${{ github.run_id }}"

      - name: Show default branch
        run: echo "默认分支 ${{ github.event.repository.default_branch }}"


      